# Interactive component

As we find that long-distance trips aren't decreasing as much as other types, we decide to lend D3 to explore more on such kind of trips. Here we use dataset2 containing monthly statistics of some transportation methods suitable for long journeys, such as airline and railway. 

First, we present an animated bar chart demonstrating comparison of total ridership of each method. The initial blue ones represent amounts in the 10 months before outbreak of COVID-19 (2019/05~2020/02) and pink ones for the next 10 months (2020/03~2020/12). With such an animation, we can see how drastically people's use of public transportation drops. Something special here is that we also include the last two groups (Freight Rail-Intermodal Units (in millions) and Freight Rail-Carloads (in millions)) as a side fact to see how freight transportation changes during pandemic. Interestingly, from the plot we can tell that effct of COVID-19 on freight is not as large as that on our daily travelling life. What's more, by hovering on the bar you are interested in, you could see the specific number!

Another thing about this chart is that comparison among different categories is not meaningful. Since dimension of each category is not on the same level, we rescale each category to produce this bar chart. For example, Airline is measure in 10 millions while ridership is in 100 millions. Please be aware of this while reading! For reference, this chart is developed following the tutorial [here](https://dev.to/plebras/want-to-learn-d3-let-s-make-a-bar-chart-3o5n).


<style type="text/css">
        svg{
            border: solid 1px #222;
        }
        svg > g.chart > rect.bar{
            fill: pink;
            stroke-width: 1px;
            stroke: #444;
            transition: fill 300ms;
        }
        svg > g.chart > rect.bar.new{
            fill: aliceblue;
        }
        svg > g.chart > rect.bar.obs{
            fill: tomato;
        }
        svg > g.chart > rect.bar.highlight{
            fill: gold;
            stroke-width: 4px;
        }
    </style>
    
<div id="barContainer"></div>

With D3, we also build a line chart with filter, through which we could choose a transportation method to see its time series over the 10 months. By functioning it as an interactive map, this would reduce a lot of area than in a static one and make us more focused on each plot. From this plot, we can get a more intuitive impression of how airline shrinks and how stable the freight traffic is. 

Please also be aware of the different scale here! The measure of each category is slightly different from last section: Airline-International and Airline-Domestic are in 0.1 millions; Ridership - Fixed Route Bus and Ridership - Urban Rail are in millions; Freight-Rail Intermodal Units and Freight-Rail Carloads are in 10 thousands. And this part is developed from [d3 gallery](https://www.d3-graph-gallery.com/graph/line_filter.html).


<select id="selectButton"></select>
<div id="my_dataviz"></div>


<script type="text/javascript" src="https://d3js.org/d3.v6.min.js"></script>
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/tippy.js@6"></script>
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>

<script type="text/javascript">
        // datasets
        let data1 = [{key: 'Airline-International (10M)', value: 10.1},
                     {key: 'Airline-Domestic (10M)', value: 71.8},
                     {key: 'Ridership-Fixed Route Bus (100M)', value: 40.6},
                     {key: 'Ridership-Urban Rail (100M)', value: 43.3},
                     {key: 'Freight Rail-Intermodal Units (M)', value: 12.1},
                     {key: 'Freight Rail-Carloads (M)', value: 11.5}];
        let data2 = [{key: 'Airline-International (10M)', value: 1.3},
                     {key: 'Airline-Domestic (10M)', value: 17.6},
                     {key: 'Ridership-Fixed Route Bus (100M)', value: 14.7},
                     {key: 'Ridership-Urban Rail (100M)', value: 8.7},
                     {key: 'Freight Rail-Intermodal Units (M)', value: 10.5},
                     {key: 'Freight Rail-Carloads (M)', value: 8.5}];
        // chart dimensions 
        let width = 600, height = 400, margin = {t:10,b:30,l:180,r:10};
        // svg element
        let svg = d3.select('div#barContainer')
            .append('svg')
            .attr('width', width)
            .attr('height', height)
            .style('border', 'solid 1px #222');
        // chart area
        let chart = svg.append('g')
            .classed('chart', true)
            .attr('transform', `translate(${margin.l},${margin.t})`);
        // axes areas
        let xAxis = svg.append('g')
            .classed('axis', true)
            .attr('transform', `translate(${margin.l},${height-margin.b})`);
        let yAxis = svg.append('g')
            .classed('axis', true)
            .attr('transform', `translate(${margin.l},${margin.t})`);
        // update function
        function updateData(dataset){
            // transitions
            let d = 500;
            let tRemove = d3.transition()
                .duration(d);
            let tPosition = d3.transition()
                .duration(d)
                .delay(d);
            let tSize = d3.transition()
                .duration(d)
                .delay(d*2);
            // scales
            let xScale = d3.scaleLinear()
                .domain([0, 75])
                .range([0, width-margin.l-margin.r]);
            let yScale = d3.scaleBand()
                .domain(dataset.map(d=>d.key))
                .range([0, height-margin.t-margin.b])
                .padding(0.2);
            // axes
            d3.axisBottom(xScale)(xAxis.transition(tSize));
            d3.axisLeft(yScale)(yAxis.transition(tPosition));
            // update pattern
            // initial selection
            bars = chart.selectAll('rect.bar');
            // data binding
            bars = bars.data(dataset, d=>d.key);
            // exit selection
            bars.exit()
                .classed('obs', true)
                .transition(tRemove)
                .attr('width', 0)
                .remove();
            // enter selection
            let barsEnter = bars.enter().append('rect')
                .classed('bar new', true)
                .attr('x', xScale(0))
                .on('mouseover', function(e,d){
                    d3.select(this).classed('highlight', true);
                })
                .on('mouseout', function(e,d){
                    d3.select(this).classed('highlight', false);
                });
            // update selection
            bars.classed('new', false);
            // enter + update selection
            bars.merge(barsEnter)
                .transition(tPosition)
                .attr('y', d=>yScale(d.key))
                .attr('height', yScale.bandwidth())
                .transition(tSize)
                .attr('width', d=>xScale(d.value));
            // class reset
            setTimeout(()=>{bars.merge(barsEnter).classed('new', false)}, d*4)
            // call tip function
            setTooltips();
        }
        // tip function
        function setTooltips(){
            // select the bars
            bars = chart.selectAll('rect.bar');
            // set the tooltip content
            bars.attr('data-tippy-content', (d,i)=>{
                return `${d.key}: ${d.value}`;
            });
            // call tippy on the bars
            tippy(bars.nodes());
        }
        setTimeout(()=>{updateData(data1)}, 2000)
        setTimeout(()=>{updateData(data2)}, 6000)
    </script>
    

<script src="https://d3js.org/d3.v4.js"></script>
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>

<script>

// set the dimensions and margins of the graph
var margin2 = {top: 10, right: 30, bottom: 30, left: 60},
    width2 = 460 - margin2.left - margin2.right,
    height2 = 400 - margin2.top - margin2.bottom;

// parse the date column
var parseTime = d3.timeParse("%Y/%m/%d");

// append the svg object to the body of the page
var svg2 = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width2 + margin2.left + margin2.right)
    .attr("height", height2 + margin2.top + margin2.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin2.left + "," + margin2.top + ")");

//Read the data
d3.csv("https://raw.githubusercontent.com/ConnieeeeeLIU/TransportationDuirngPandemic/main/data/clean/monthly_stats_d3.csv", function(data) {

    // call parse time function
    data.forEach(function(d) {
      d.date = parseTime(d.date);
    });

    // List of groups (here I have one group per column)
    var allGroup = d3.map(data, function(d){return(d.TransportationMethod)}).keys()

    // add the options to the button
    d3.select("#selectButton")
      .selectAll('myOptions')
      .data(allGroup)
      .enter()
      .append('option')
      .text(function (d) { return d; }) // text showed in the menu
      .attr("value", function (d) { return d; }) // corresponding value returned by the button

    // A color scale: one color for each group
    var myColor = d3.scaleOrdinal()
      .domain(allGroup)
      .range(d3.schemeSet2);

    // Add X axis --> it is a date format
    var x = d3.scaleTime()
      .domain(d3.extent(data, function(d) { return d.date; }))
      .range([ 0, width2 ]);
    svg2.append("g")
      .attr("transform", "translate(0," + height2 + ")")
      .call(d3.axisBottom(x).ticks(7));

    // Add Y axis
    var y = d3.scaleLinear()
      .domain([0, d3.max(data, function(d) { return +d.Frequency; })])
      .range([ height2, 0 ]);
    svg2.append("g")
      .call(d3.axisLeft(y));

    // Initialize line with first group of the list
    var line = svg2
      .append('g')
      .append("path")
        .datum(data.filter(function(d){return d.TransportationMethod==allGroup[0]}))
        .attr("d", d3.line()
          .x(function(d) { return x(d.date) })
          .y(function(d) { return y(+d.Frequency) })
        )
        .attr("stroke", function(d){ return myColor("valueA") })
        .style("stroke-width", 4)
        .style("fill", "none")

    // A function that update the chart
    function update(selectedGroup) {

      // Create new data with the selection?
      var dataFilter = data.filter(function(d){return d.TransportationMethod==selectedGroup})

      //let yScale = d3.scaleLinear()
       //         .domain([0, d3.max(data, function(d) { return +d.Frequency; })])
       //         .range([height2, 0]);
       //d3.axisLeft(yScale)(y);


      // Give these new data to update line
      line
          .datum(dataFilter)
          .transition()
          .duration(1000)
          .attr("d", d3.line()
            .x(function(d) { return x(d.date) })
            .y(function(d) { return y(+d.Frequency) })
          )
          .attr("stroke", function(d){ return myColor(selectedGroup) })
    }

    // When the button is changed, run the updateChart function
    d3.select("#selectButton").on("change", function(d) {
        // recover the option that has been chosen
        var selectedOption = d3.select(this).property("value")
        // run the updateChart function with this selected option
        update(selectedOption)
    })

})


</script>